name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # هنرجع للأحدث ونستخدم الأداة الرسمية

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer Action
        uses: ArtemShatalov/buildozer-action@v1.6.1 # أحدث نسخة مستقرة ومجربة
        with:
          command: buildozer android debug
          buildozer_version: master
          python_version: 3.11

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Noser_App_Final
          path: bin/*.apk
