name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # هنرجع للأحدث ونستخدم الأداة الرسمية

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Buildozer Action
        uses: kivy/buildozer-action@v1.2.3
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Noser_App_Final
          path: bin/*.apk
